{{- if .Values.operator.enabled }}
{{- if .Values.operator.cluster }}
apiVersion: storage.simplyblock.io/v1alpha1
kind: StorageCluster
metadata:
  name: {{ .Values.operator.cluster.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Values.operator.cluster.clusterName }}

  {{- if .Values.operator.cluster.mgmtIfname }}
  mgmtIfname: {{ .Values.operator.cluster.mgmtIfname }}
  {{- end }}

  {{- if .Values.operator.cluster.fabricType }}
  fabricType: {{ .Values.operator.cluster.fabricType }}
  {{- end }}

  {{- if hasKey .Values.operator.cluster "isSingleNode" }}
  isSingleNode: {{ .Values.operator.cluster.isSingleNode }}
  {{- end }}

  {{- if hasKey .Values.operator.cluster "enableNodeAffinity" }}
  enableNodeAffinity: {{ .Values.operator.cluster.enableNodeAffinity }}
  {{- end }}

  {{- if hasKey .Values.operator.cluster "strictNodeAntiAffinity" }}
  strictNodeAntiAffinity: {{ .Values.operator.cluster.strictNodeAntiAffinity }}
  {{- end }}

  {{- with .Values.operator.cluster.stripe }}
  {{- if or .dataChunks .parityChunks }}
  stripe:
    {{- if .dataChunks }}
    dataChunks: {{ .dataChunks }}
    {{- end }}
    {{- if .parityChunks }}
    parityChunks: {{ .parityChunks }}
    {{- end }}
  {{- end }}
  {{- end }}

  {{- if .Values.operator.cluster.qpairCount }}
  qpairCount: {{ .Values.operator.cluster.qpairCount }}
  {{- end }}

  {{- if .Values.operator.cluster.clientQpairCount }}
  clientQpairCount: {{ .Values.operator.cluster.clientQpairCount }}
  {{- end }}

  {{- if .Values.operator.cluster.haType }}
  haType: {{ .Values.operator.cluster.haType }}
  {{- end }}

  {{- if .Values.operator.cluster.blockSize }}
  blockSize: {{ .Values.operator.cluster.blockSize }}
  {{- end }}

  {{- if .Values.operator.cluster.pageSizeInBlocks }}
  pageSizeInBlocks: {{ .Values.operator.cluster.pageSizeInBlocks }}
  {{- end }}

  {{- if .Values.operator.cluster.maxQueueSize }}
  maxQueueSize: {{ .Values.operator.cluster.maxQueueSize }}
  {{- end }}

  {{- if .Values.operator.cluster.inflightIOThreshold }}
  inflightIOThreshold: {{ .Values.operator.cluster.inflightIOThreshold }}
  {{- end }}

  {{- if .Values.operator.cluster.clientDataIfname }}
  clientDataIfname: {{ .Values.operator.cluster.clientDataIfname }}
  {{- end }}

  {{- if .Values.operator.cluster.maxFaultTolerance }}
  maxFaultTolerance: {{ .Values.operator.cluster.maxFaultTolerance }}
  {{- end }}

  {{- if .Values.operator.cluster.nvmfBasePort }}
  nvmfBasePort: {{ .Values.operator.cluster.nvmfBasePort }}
  {{- end }}

  {{- if .Values.operator.cluster.rpcBasePort }}
  rpcBasePort: {{ .Values.operator.cluster.rpcBasePort }}
  {{- end }}

  {{- if .Values.operator.cluster.snodeApiPort }}
  snodeApiPort: {{ .Values.operator.cluster.snodeApiPort }}
  {{- end }}

  {{- if .Values.operator.cluster.qosClasses }}
  qosClasses: {{ .Values.operator.cluster.qosClasses | quote }}
  {{- end }}

  {{- if .Values.operator.cluster.warningThreshold }}
  warningThreshold:
    {{- if .Values.operator.cluster.warningThreshold.capacity }}
    capacity: {{ .Values.operator.cluster.warningThreshold.capacity }}
    {{- end }}
    {{- if .Values.operator.cluster.warningThreshold.provisionedCapacity }}
    provisionedCapacity: {{ .Values.operator.cluster.warningThreshold.provisionedCapacity }}
    {{- end }}
  {{- end }}

  {{- if .Values.operator.cluster.criticalThreshold }}
  criticalThreshold:
    {{- if .Values.operator.cluster.criticalThreshold.capacity }}
    capacity: {{ .Values.operator.cluster.criticalThreshold.capacity }}
    {{- end }}
    {{- if .Values.operator.cluster.criticalThreshold.provisionedCapacity }}
    provisionedCapacity: {{ .Values.operator.cluster.criticalThreshold.provisionedCapacity }}
    {{- end }}
  {{- end }}

{{- end }}

---
{{- if .Values.operator.pool }}
apiVersion: storage.simplyblock.io/v1alpha1
kind: Pool
metadata:
  name: {{ .Values.operator.pool.name }}
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.operator.pool.name }}
  clusterName: {{ .Values.operator.cluster.clusterName }}

  {{- if .Values.operator.pool.capacityLimit }}
  capacityLimit: {{ .Values.operator.pool.capacityLimit | quote }}
  {{- end }}

  {{- if .Values.operator.pool.qos }}
  qos:
    {{- if .Values.operator.pool.qos.iops }}
    iops: {{ .Values.operator.pool.qos.iops }}
    {{- end }}
    {{- if .Values.operator.pool.qos.throughput }}
    throughput:
      {{- if .Values.operator.pool.qos.throughput.read }}
      read: {{ .Values.operator.pool.qos.throughput.read }}
      {{- end }}
      {{- if .Values.operator.pool.qos.throughput.readWrite }}
      readWrite: {{ .Values.operator.pool.qos.throughput.readWrite }}
      {{- end }}
      {{- if .Values.operator.pool.qos.throughput.write }}
      write: {{ .Values.operator.pool.qos.throughput.write }}
      {{- end }}
    {{- end }}
  {{- end }}

{{- end }}

---
{{- if .Values.operator.lvol }}
apiVersion: storage.simplyblock.io/v1alpha1
kind: Lvol
metadata:
  name: {{ .Values.operator.lvol.name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Values.operator.cluster.clusterName }}
  poolName: {{ .Values.operator.pool.name }}
{{- end }}

---
{{- if .Values.operator.storageNodes }}
apiVersion: storage.simplyblock.io/v1alpha1
kind: StorageNode
metadata:
  name: {{ .Values.operator.storageNodes.name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Values.operator.cluster.clusterName }}

  clusterImage: "{{ .Values.image.simplyblock.repository }}:{{ .Values.image.simplyblock.tag }}" 

  {{- if .Values.operator.storageNodes.mgmtIfname }}
  mgmtIfname: {{ .Values.operator.storageNodes.mgmtIfname }}
  {{- end }}

  {{- if .Values.operator.storageNodes.spdkImage }}
  spdkImage: {{ .Values.operator.storageNodes.spdkImage }}
  {{- end }}

  {{- if .Values.operator.storageNodes.maxLogicalVolumeCount }}
  maxLogicalVolumeCount: {{ .Values.operator.storageNodes.maxLogicalVolumeCount }}
  {{- end }}

  {{- if .Values.operator.storageNodes.maxSize }}
  maxSize: {{ .Values.operator.storageNodes.maxSize | quote }}
  {{- end }}

  {{- if not (kindIs "invalid" .Values.operator.storageNodes.partitions) }}
  partitions: {{ .Values.operator.storageNodes.partitions }}
  {{- end }}
  
  {{- if .Values.operator.storageNodes.corePercentage }}
  corePercentage: {{ .Values.operator.storageNodes.corePercentage }}
  {{- end }}

  {{- with .Values.operator.storageNodes.journalManager }}
  {{- if or .count .percentPerDevice .useSeparateJournalDevice }}
  journalManager:
    {{- if .count }}
    count: {{ .count }}
    {{- end }}
    {{- if .percentPerDevice }}
    percentPerDevice: {{ .percentPerDevice }}
    {{- end }}
    {{- if .useSeparateJournalDevice }}
    useSeparateJournalDevice: {{ .useSeparateJournalDevice }}
    {{- end }}
  {{- end }}
  {{- end }}

  {{- if hasKey .Values.operator.storageNodes "coreIsolation" }}
  coreIsolation: {{ .Values.operator.storageNodes.coreIsolation }}
  {{- end }}

  {{- if .Values.operator.storageNodes.pcieAllowList }}
  pcieAllowList:
  {{- range .Values.operator.storageNodes.pcieAllowList }}
    - {{ . }}
  {{- end }}
  {{- end }}

  {{- if .Values.operator.storageNodes.pcieDenyList }}
  pcieDenyList:
  {{- range .Values.operator.storageNodes.pcieDenyList }}
    - {{ . }}
  {{- end }}
  {{- end }}

  {{- if .Values.operator.storageNodes.pcieModel }}
  pcieModel: {{ .Values.operator.storageNodes.pcieModel }}
  {{- end }}

  {{- if .Values.operator.storageNodes.driveSizeRange }}
  driveSizeRange: {{ .Values.operator.storageNodes.driveSizeRange }}
  {{- end }}

  {{- if .Values.operator.storageNodes.socketsToUse }}
  socketsToUse:
  {{- range .Values.operator.storageNodes.socketsToUse }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}

  {{- if .Values.operator.storageNodes.nodesPerSocket }}
  nodesPerSocket: {{ .Values.operator.storageNodes.nodesPerSocket }}
  {{- end }}

  {{- if .Values.operator.storageNodes.dataIfname }}
  dataIfname:
  {{- range .Values.operator.storageNodes.dataIfname }}
    - {{ . }}
  {{- end }}
  {{- end }}

  {{- if hasKey .Values.operator.storageNodes "skipKubeletConfiguration" }}
  skipKubeletConfiguration: {{ .Values.operator.storageNodes.skipKubeletConfiguration }}
  {{- end }}

  {{- if hasKey .Values.operator.storageNodes "enableCpuTopology" }}
  enableCpuTopology: {{ .Values.operator.storageNodes.enableCpuTopology }}
  {{- end }}


  {{- if hasKey .Values.operator.storageNodes "openShiftCluster" }}
  openShiftCluster: {{ .Values.operator.storageNodes.openShiftCluster }}
  {{- end }}

  {{- if hasKey .Values.operator.storageNodes "ubuntuHost" }}
  ubuntuHost: {{ .Values.operator.storageNodes.ubuntuHost }}
  {{- end }}

  {{- if hasKey .Values.operator.storageNodes "forceFormat4K" }}
  forceFormat4K: {{ .Values.operator.storageNodes.forceFormat4K }}
  {{- end }}

  {{- if .Values.operator.storageNodes.reservedSystemCPU }}
  reservedSystemCPU: {{ .Values.operator.storageNodes.reservedSystemCPU }}
  {{- end }}

  {{- if .Values.operator.storageNodes.deviceNames }}
  deviceNames:
  {{- range .Values.operator.storageNodes.deviceNames }}
    - {{ . }}
  {{- end }}
  {{- end }}

  {{- if .Values.operator.storageNodes.workerNodes }}
  workerNodes:
  {{- range .Values.operator.storageNodes.workerNodes }}
    - {{ . }}
  {{- end }}
  {{- end }}

  {{- if and .Values.operator.storageNodes.tolerations .Values.operator.storageNodes.tolerations.create }}
  tolerations:
  {{- range .Values.operator.storageNodes.tolerations.list }}
    - {{- if .key }}
      key: {{ .key | quote }}
      {{- end }}
      operator: {{ default "Exists" .operator }}
      {{- if .value }}
      value: {{ .value | quote }}
      {{- end }}
      {{- if .effect }}
      effect: {{ .effect }}
      {{- end }}
  {{- end }}
  {{- end }}

{{- end }}

---
{{- if .Values.operator.devices }}
apiVersion: storage.simplyblock.io/v1alpha1
kind: Device
metadata:
  name: {{ .Values.operator.devices.name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Values.operator.cluster.clusterName }}
{{- end }}

---
{{- if .Values.operator.tasks }}
apiVersion: storage.simplyblock.io/v1alpha1
kind: Task
metadata:
  name: {{ .Values.operator.tasks.name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Values.operator.cluster.clusterName }}
{{- end }}
{{- end }}
