{{- if .Values.storagenode.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simplyblock-storage-node-service-account

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplyblock-storage-node-controller
  labels:
    app: storage-node-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-node-controller
  template:
    metadata:
      labels:
        app: storage-node-controller
    spec:
      serviceAccountName: simplyblock-storage-node-service-account
      containers:
      - name: storage-node-controller
        image: "{{ .Values.image.storageNode.repository }}:{{ .Values.image.storageNode.tag }}"
        imagePullPolicy: "{{ .Values.image.storageNode.pullPolicy }}"
        env:
        - name: SPDKCSI_SECRET
          valueFrom:
            secretKeyRef:
              name: simplyblock-csi-secret
              key: secret.json
        - name: CLUSTER_CONFIG
          valueFrom:
            configMapKeyRef:
              name: simplyblock-csi-cm
              key: config.json
        - name: IFNAME
          value: "{{- if kindIs "string" .Values.storagenode.ifname -}}
                    {{ .Values.storagenode.ifname }}
                  {{- else -}}
                    {{ join "," .Values.storagenode.ifname }}
                  {{- end -}}"
        - name: MAXSNAP
          value: "{{ .Values.storagenode.maxSnapshots }}"
        - name: JMPERCENT
          value: "3"
        - name: NUMPARTITIONS
          value: "{{ .Values.storagenode.numPartitions }}"
        - name: DISABLEHAJM
          value: "false"
        - name: ENABLETESTDEVICE
          value: "false"
        - name: DATANICS
          value: "{{ .Values.storagenode.dataNics }}"
        - name: SPDKIMAGE
          value: "{{ .Values.storagenode.spdkImage }}"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      restartPolicy: Always

{{- end -}}
