kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spdkcsi-cache-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: simplyblock-csi-sc-cache
