apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    annotations:
        simplybk/secret-name: simplyblock-pvc-keys
        simplybk/secret-namespace: spdk-csi
    name: spdkcsi-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: simplyblock-csi-sc
